Repository vtex-apps/telemarketing, pull requests merged in 2019-03, with the labels that each got.

#38 Upgrade test suite adding more tests
  CHANGELOG.md
  react/__mocks__/vtex.styleguide.tsx
  react/__tests__/Telemarketing.test.tsx
  react/__tests__/__snapshots__/Telemarketing.test.tsx.snap
Labels: chore

#35 Fix style
  CHANGELOG.md
  manifest.json
  react/__mocks__/vtex.render-runtime.tsx
  react/__tests__/Telemarketing.test.tsx
  react/__tests__/__snapshots__/Telemarketing.test.tsx.snap
  react/components/LoginAsCustomer.tsx
  react/components/LogoutCustomerSession.tsx
  react/components/Popover.tsx
  react/components/Telemarketing.tsx
  react/hooks/useMedia.tsx
  react/hooks/useOutsideClick.tsx
  react/index.tsx
  react/package.json
  react/telemarketing.css
  react/typings/render.d.ts
  react/typings/vtex.store-icons.d.ts
  react/yarn.lock
Labels: bug, chore, enhancement

#42 Fix infinite loop due useCallback wrong dependency
  CHANGELOG.md
  manifest.json
  react/index.tsx
Labels: bug

#44 Using tokens to define responsive width
  CHANGELOG.md
  manifest.json
  react/__tests__/__snapshots__/Telemarketing.test.tsx.snap
  react/components/LoginAsCustomer.tsx
  react/components/Popover.tsx
Labels: chore
