Repository vtex-apps/telemarketing, pull requests merged in 2019-01, with the labels that each got.

#26 Bye pages.json! Welcome store-builder
  CHANGELOG.md
  manifest.json
  pages/pages.json
  react/components/LogoutCustomerSession.tsx
  react/index.tsx
  react/typings/vtex.store-resources.d.ts
  store/blocks.json
  store/interfaces.json
Labels: enhancement

#27 Remove undefined class
  CHANGELOG.md
  manifest.json
  react/telemarketing.css
Labels: bug

#28 Add Container for adjusting search result to store padding
  CHANGELOG.md
  manifest.json
  react/components/Telemarketing.tsx
  react/typings/render.d.ts
  react/typings/vtex.store-components.d.ts
  react/typings/vtex.use-svg.d.ts
Labels: chore
